security:
    encoders:
        BcTic\VictoriaBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        bctic_victoria_bundle:
            entity: { class: BcTic\VictoriaBundle\Entity\User, property: username }  

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                provider: bctic_victoria_bundle
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_ADMIN }
